"""empty message

Revision ID: 8a9bccfe661a
Revises: 
Create Date: 2018-09-10 20:21:19.221905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9bccfe661a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('USER')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USER',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('NAME', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )

    op.drop_table('user')
    # ### end Alembic commands ###
